stages:
  - warmup
  - build
  - deploy

cache:
  paths:
    - node_modules/

warmup:
  stage: warmup
  script: ls
  tags:
    - macos

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r packages/app/desktop/build/installers/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*_mac.dmg
      - public/*_mac.zip
  tags:
    - macos
  rules:
    - when: never

build:
  stage: build
  script:
    - npm i
    - npm run dist-mac
    - npm run dist-mac-notarize
  tags:
    - macos
  rules:
    - when: never
