stages:
  - warmup
  - e2e
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
    - npm install

      #e2e:
      #  stage: e2e
      #  image: tijnschmits/chromium-xvfb-js-java8
      #  script:
      #    - npm run _react-build
      #    - npm run test

warmup:
  stage: warmup
  script: ls
  tags:
    - macos

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r packages/app/desktop/build/installers/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*_mac.dmg
      - public/*_mac.zip
  tags:
    - macos
  rules:
    - when: never

build:
  stage: build
  script:
    - npm i
    - npm run dist-mac
    - npm run dist-mac-notarize
  tags:
    - macos
  rules:
    - when: never
