language: node_js

node_js:
  - '8'

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx

cache: npm

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git-core; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libssl-dev; fi
  - npm install

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run dist-linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm run dist-mac; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "dist/hokus-cms_linux_amd64.snap"
    - "dist/hokus-cms_linux_x86_64.AppImage"
    - "hokus-cms_linux_amd64.deb"
  draft: true
  on:
    condition: $TRAVIS_OS_NAME = linux
      # tags: true 
  # - provider: releases
  #   api_key: $GITHUB_OAUTH_TOKEN
  #   file:
  #     - "FILE TO UPLOAD"
  #     - "FILE TO UPLOAD"
  #   draft: true
  #   on:
  #     tags: true
  #     condition: "$TRAVIS_OS_NAME" == "osx"