language: node_js

node_js:
  - '8'

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required

cache: npm

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git-core; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libssl-dev; fi
  - npm install

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm run dist-linux; fi