buildDrafts: true
outputs:
  home:
    - Sukoh
    - Zpogomenu
outputFormats:
  Sukoh:
    mediaType: "application/json"
    baseName: "sukoh"
    path: "/"
  Zpogomenu:
    mediaType: "application/json"
    baseName: "zpogomenu"
    path: "/"
