---
subject: some subject
from: you-have-mail@pogoform.com
to: info@example.com
redirect_to: /form-sent
validations:
  fields:
    email:
      type: email
      empty: false
      mandatory: true
    name:
      type: string
      empty: false
      mandatory: true
    lastName:
      type: string
      empty: true
      mandatory: true
    message:
      type: string
      empty: false
      mandatory: true
